plugins {
    id 'com.android.application'
}

android {
    namespace 'wang.w2334681436.politics.timeline'
    compileSdk 35

    defaultConfig {
        applicationId 'wang.w2334681436.politics.timeline'
        minSdk 23
        targetSdk 35
        versionCode 3
        versionName '1.2-offline'
    }

    buildTypes {
        debug {
            debuggable false
            applicationIdSuffix ''
            versionNameSuffix ''
        }
        release {
            minifyEnabled false
            shrinkResources false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
